################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Each subdirectory must supply rules for building sources it contributes
HardwareAbstractions/Adc_10.obj: ../HardwareAbstractions/Adc_10.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/Adc_10.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HardwareAbstractions/GpioGroup.obj: ../HardwareAbstractions/GpioGroup.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/GpioGroup.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HardwareAbstractions/HeartbeatLed.obj: ../HardwareAbstractions/HeartbeatLed.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/HeartbeatLed.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HardwareAbstractions/Interrupt_1MsSystemTick.obj: ../HardwareAbstractions/Interrupt_1MsSystemTick.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/Interrupt_1MsSystemTick.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HardwareAbstractions/LcdDisplayParallel2Line.obj: ../HardwareAbstractions/LcdDisplayParallel2Line.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/LcdDisplayParallel2Line.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HardwareAbstractions/Spi.obj: ../HardwareAbstractions/Spi.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/Spi.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HardwareAbstractions/StepperMotor.obj: ../HardwareAbstractions/StepperMotor.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/StepperMotor.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HardwareAbstractions/TimeSource_Interrupt1MsSystemTick.obj: ../HardwareAbstractions/TimeSource_Interrupt1MsSystemTick.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/TimeSource_Interrupt1MsSystemTick.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '

HardwareAbstractions/WaveformGenerator.obj: ../HardwareAbstractions/WaveformGenerator.c $(GEN_OPTS) | $(GEN_HDRS)
	@echo 'Building file: "$<"'
	@echo 'Invoking: MSP430 Compiler'
	"/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/bin/cl430" -vmsp -O0 --opt_for_speed=0 --use_hw_mpy=none --include_path="/Applications/ti/ccsv7/ccs_base/msp430/include" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Input" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Models" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Controllers" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/DataStructures" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Event" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/HardwareAbstractions" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Timer" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/TimerModule" --include_path="/Users/gaboth22/Documents/workspace/FinalProject/Utilities" --include_path="/Users/gaboth22/Documents/workspace/FinalProject" --include_path="/Applications/ti/ccsv7/tools/compiler/ti-cgt-msp430_16.9.6.LTS/include" --advice:power=all --define=__MSP430F2274__ -g --printf_support=minimal --diag_warning=225 --diag_wrap=off --display_error_number --silicon_errata=CPU19 --preproc_with_compile --preproc_dependency="HardwareAbstractions/WaveformGenerator.d_raw" --obj_directory="HardwareAbstractions" $(GEN_OPTS__FLAG) "$<"
	@echo 'Finished building: "$<"'
	@echo ' '


